# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LittlePink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LittlePink
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'CHTCollectionViewWaterfallLayout/ObjC'
  pod 'YPImagePicker'
  pod 'MBProgressHUD', '~>1.2.0'
  pod 'SKPhotoBrowser'
  pod 'KMPlaceholderTextView', '~> 1.4.0'

end

# 覆盖所有 Pod 的最低版本（重要）
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
    end
  end
end
